export const SCOREBOARD_FETCH_REQUEST = 'SCOREBOARD_FETCH_REQUEST';
export const SCOREBOARD_FETCH_SUCCESS = 'SCOREBOARD_FETCH_SUCCESS';
export const SCOREBOARD_FETCH_FAILURE = 'SCOREBOARD_FETCH_FAILURE';

export const SCOREBOARD_UPDATE_REQUEST = 'SCOREBOARD_UPDATE_REQUEST';
export const SCOREBOARD_UPDATE_SUCCESS = 'SCOREBOARD_UPDATE_SUCCESS';
export const SCOREBOARD_UPDATE_FAILURE = 'SCOREBOARD_UPDATE_FAILURE';

export const SCORE_SAVE_REQUEST = 'SCORE_SAVE_REQUEST';
export const SCORE_SAVE_SUCCESS = 'SCORE_SAVE_SUCCESS';
export const SCORE_SAVE_FAILURE = 'SCORE_SAVE_FAILURE';

export const SESSIONS_COMPLETED_FETCH_REQUEST = 'SESSIONS_COMPLETED_FETCH_REQUEST';
export const SESSIONS_COMPLETED_FETCH_SUCCESS = 'SESSIONS_COMPLETED_FETCH_SUCCESS';
export const SESSIONS_COMPLETED_FETCH_FAILURE = 'SESSIONS_COMPLETED_FETCH_FAILURE';
