export const SCOREBOARD_UPDATE_REQUEST = 'SCOREBOARD_UPDATE_REQUEST';
export const SCOREBOARD_UPDATE_SUCCESS = 'SCOREBOARD_UPDATE_SUCCESS';
export const SCOREBOARD_UPDATE_FAILURE = 'SCOREBOARD_UPDATE_FAILURE';

